apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdu-deploy
  labels:
    app: cdu-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cdu-server
  template:
    metadata:
      name: cdu-server
      labels:
        app: cdu-server
    spec:
      containers:
        - name: cdu-server
          image: eakkaya64/web-server
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mysql-admin-password
          envFrom:
          - configMapRef:
              name: servers-configmap


---


apiVersion: v1
kind: Service
metadata:
  name: cdu-server-svc
  labels:
    app: cdu-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: cdu-server